[@ww.textfield labelKey="net.ceg.bamboo.connection.path" name="connection" required='true'/]
[@ww.checkbox labelKey="net.ceg.bamboo.artifact.path" name="artifact" required='true'/]
[@ww.textfield labelKey="net.ceg.bamboo.artifactRegex.path" name="artifactRegex" required='false'/]
[@ww.textfield labelKey="net.ceg.bamboo.config.path" name="path" required='true'/]
[@ww.textfield labelKey="net.ceg.bamboo.config.data" name="data" required='true'/]